### ISSUE TITLE
Api endpoint description is not correct

### ISSUE THREAD

**Issue by bekuno** [GeoKretyMap/gkm#1]
1. The api endpoints lists the method:

| /wpt/{$wpt}/details | Full by waypoint | public | https://api.geokretymap.org/wpt/GC5BRQK/details |

This is not defined in
https://github.com/GeoKretyMap/gkm-api-nginx/blob/master/conf.d/api.geokretymap.org.conf

and does not work.

2. The api endpoints lists the method:

| /nr2id.php?nr={$nr} | Alias for Basic by Secret Code. (deprecated) | public | https://api.geokretymap.org/export-details.php?nr2id.php?nr=THESECRET |

This has a syntax error.
It should be 
https://api.geokretymap.org/nr2id.php?nr=THESECRET

**Comment by kumy** [comment]
Point 1. should be fixed;
* https://api.geokretymap.org/wpt/GC5BRQK
* https://api.geokretymap.org/wpt/GC5BRQK/details

**Comment by kumy** [comment]
2. fixed.

@bekuno Thanks for the report
