### ISSUE TITLE
  Api endpoint description is not correct (next typo)

### ISSUE THREAD

**Issue by bekuno** [GeoKretyMap/gkm#2]
In this line:
/nr2id/{$nr} | Get only the corresponding {$gkid} ; not the full .xml | public | https://api.geokretymap.org/gkwpt/46464/nr2id/THESECRET |

the sample should be changed to: 
  https://api.geokretymap.org/nr2id/THESECRET

**Comment by kumy** [comment]
Bad copy/paste, thanks for the hint!
